### PR TITLE
#161342792 Setup redux

### PR DESCRIPTION
**Pull request by victor-nweze-deel**
#### What does this PR do?
Setup Redux

#### Description of Task to be completed?
- Install Redux, react-redux and redux-saga
- Setup folder structure for a react/redux workflow

#### What are the relevant pivotal tracker stories?
[#161342792](https://www.pivotaltracker.com/story/show/161342792)

### CODE REVIEW

**Comment by PriscillaSam** [comment]
The setup looks appropriate. Well done @ProfJigsaw

**Comment by wiztemple** [comment]
@ProfJigsaw, good set up. good to go.

**Comment by seyi-adeleke** [comment]
Whats the difference between layouts and views?

**Comment by victor-nweze-deel** [comment]
> Whats the difference between layouts and views?

Layouts define the structure for a component and views are contained within. An example of this would be a `MainLayout.jsx` defining the position of the navbar, the sections and asides as follows:
```
...
return (
  <div>
    <Navbar />
    <Aside />
    <MainSection> {this.props.children} </MainSection>
    . . .
    <Footer />
  </div>
);
```
The different components called then render `containers` which may or may not be connected to redux and then the views do the actual `html` element rendering.

**Review by seyi-adeleke — APPROVED** [review]

**Pull request merged**
